#include <iostream>
#include <string>
#include "sgx_urts.h"
#include "Enclave_u.h" // Headers for untrusted part (autogenerated by edger8r)

using namespace std;

// ocalls for printing string (C++ ocalls)
void ocall_print_error(const char *str){
    cerr << str << endl;
}

// void ocall_print_string(const char *str){
//     cout << str;
// }

// void ocall_println_string(const char *str){
//     cout << str << endl;
// }