load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "sgx_types",
    visibility = ["//visibility:public"],
    edition = "2018",
    srcs = glob(["src/*.rs"]),
    deps = [],
)