#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

COV_RUSTFLAGS="-Zprofile -Ccodegen-units=1 \
    -Cllvm_args=-inline-threshold=0 -Clink-dead-code \
    -Coverflow-checks=off -Cpanic=abort"

get_crate_name()
{
    while [[ $# -gt 1 ]] ; do
        v=$1
        case $v in
            --crate-name)
                echo $2
                return
            ;;
        esac
        shift
    done
}

case $(get_crate_name "$@") in
    cov)
        EXTRA=${COV_RUSTFLAGS}
    ;;
    *)
        EXTRA=
    ;;
esac

exec "$@" $EXTRA
